import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import About from "./components/about";
import SkillsPage from "./components/skills";
import Experience from "./components/experience";
import Projects from "./components/projects";
import Testimonials from "./components/testimonials";
import Reachout from "./components/reachout";
import Footer from "./components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pritam Das Adhikari - Software Developer Portfolio",
  description: "Generated by create next app",
    icons: {
    icon: "/assets/logo.jpg", // path from public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <About />
        <SkillsPage />
        <Projects />
        <Experience />
        <Testimonials />
        <Reachout />
        <Footer />
      </body>
    </html>
  );
}
